version: "3.9"

services:

  bot:
    build:
      context: cludus
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - dashboard
    environment:
      DASHBORD_URL: "http://dashboard:3000/"
    networks:
      - default

  dashboard:
    build:
      context: dashboard
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      MONGO_USERNAME: root
      MONGO_PASSWORD: password
      MONGO_URL: mongodb://root:password@mongo:27017/
    networks:
      - default

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    networks:
      - default

volumes:
  mongo-data:

networks:
  default:
